version: '3'
services:
  react:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - C:/Dev/Quiz_Time/client/:/workspace
      - /workspace/node_modules